# Generated by Django 4.2.7 on 2023-12-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bank_country_alter_userprofile_user_parents_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
