# Generated by Django 4.2.7 on 2023-12-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='comapny_type',
            new_name='company_type',
        ),
    ]
