# Generated by Django 4.2.7 on 2023-12-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_comapny_type_company_company_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='account_holser_name',
            new_name='account_holder_name',
        ),
    ]
