# Generated by Django 4.2.7 on 2023-12-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_account_holser_name_bankaccount_account_holder_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_tye',
            new_name='address_type',
        ),
    ]
